name: HomeTask from Luminor

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  chrome_build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1

      - name: Gradle clean
        run: |
          ./gradlew clean

      - name: TestSuite execution
        run: |
          ./gradlew testSuite

      - name: Generate allure reports
        if: success() || failure()
        run: |
          ./gradlew allureReport

      - name: Add allure report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: Allure reports HomeTask
          path: build/reports/allure-report/allureReport

      - name: Add cucumber report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: Cucumber reports HomeTask
          path: target/cucumber-report.html
